//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace U_LearningNET.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Materials
    {
        public int material_id { get; set; }
        public Nullable<int> course_id { get; set; }
        public string title { get; set; }
        public string file_url { get; set; }
        public Nullable<System.DateTime> uploaded_at { get; set; }
    
        public virtual Courses Courses { get; set; }
    }
}
